import type { RobotAction } from './types';
import { ROBOT_SPEC } from './robotSpec';

/**
 * 预置动作库。
 * 约定：每个动作的 keyframes 必须覆盖 t=0 与 t=1；
 * pose 中省略的字段自动继承上一关键帧，最终以 NEUTRAL_POSE 兜底。
 * 新增动作只需往此数组追加对象，无需改动引擎。
 */
export const ACTION_LIBRARY: RobotAction[] = [
  // ───────────────────────── 头部 / 云台 ─────────────────────────
  {
    id: 'head.look_at',
    label: '看向目标方向',
    aliases: ['看', '看向', '转身看', 'look at', '转头'],
    description: '云台水平转到指定角度，可同时带上仰或俯视。',
    actuators: ['head'],
    durationMs: 700,
    interruptible: true,
    priority: 30,
    params: [
      {
        name: 'yaw',
        description: '目标水平角度，度，-90 到 90，正为右',
        type: 'number',
        required: true,
        default: 0,
        min: -90,
        max: 90,
      },
      {
        name: 'pitch',
        description: '目标俯仰角度，度，-45 到 45，正为抬头',
        type: 'number',
        required: false,
        default: 0,
        min: -45,
        max: 45,
      },
    ],
    keyframes: [
      { t: 0, pose: {} },
      { t: 0.45, pose: { headYaw: 0, headPitch: 0 } },
      { t: 1, pose: { headYaw: 0, headPitch: 0 } },
    ],
  },
  {
    id: 'head.nod',
    label: '点头',
    aliases: ['点头', 'yes', '同意', 'nod', '嗯'],
    description: '上下点头两下，表示同意或确认。',
    actuators: ['head'],
    durationMs: 900,
    interruptible: true,
    priority: 40,
    params: [
      {
        name: 'times',
        description: '点头次数，1 到 3',
        type: 'number',
        required: false,
        default: 2,
        min: 1,
        max: 3,
      },
    ],
    keyframes: [
      { t: 0, pose: { headPitch: 0 } },
      { t: 0.18, pose: { headPitch: 22 } },
      { t: 0.32, pose: { headPitch: -4 } },
      { t: 0.5, pose: { headPitch: 20 } },
      { t: 0.68, pose: { headPitch: 0 } },
      { t: 1, pose: { headPitch: 0 } },
    ],
    emotion: 'happy',
  },
  {
    id: 'head.shake',
    label: '摇头',
    aliases: ['摇头', 'no', '否定', '拒绝', 'shake', '不同意'],
    description: '左右摇头两下，表示否定或拒绝。',
    actuators: ['head'],
    durationMs: 900,
    interruptible: true,
    priority: 40,
    params: [
      {
        name: 'times',
        description: '摇头次数，1 到 3',
        type: 'number',
        required: false,
        default: 2,
        min: 1,
        max: 3,
      },
    ],
    keyframes: [
      { t: 0, pose: { headYaw: 0 } },
      { t: 0.18, pose: { headYaw: -24 } },
      { t: 0.32, pose: { headYaw: 24 } },
      { t: 0.5, pose: { headYaw: -20 } },
      { t: 0.68, pose: { headYaw: 0 } },
      { t: 1, pose: { headYaw: 0 } },
    ],
    emotion: 'sad',
  },
  {
    id: 'head.tilt',
    label: '歪头',
    aliases: ['歪头', '侧头', '好奇', 'tilt', '疑惑'],
    description: '头部侧倾并微微前倾，配合好奇或疑惑的情绪。',
    actuators: ['head'],
    durationMs: 800,
    interruptible: true,
    priority: 35,
    params: [
      {
        name: 'direction',
        description: '歪头方向',
        type: 'enum',
        required: false,
        default: 'left',
        options: ['left', 'right'],
      },
    ],
    keyframes: [
      { t: 0, pose: { headRoll: 0, headPitch: 0 } },
      { t: 0.5, pose: { headRoll: 18, headPitch: 6 } },
      { t: 0.8, pose: { headRoll: 16, headPitch: 5 } },
      { t: 1, pose: { headRoll: 16, headPitch: 5 } },
    ],
    emotion: 'curious',
  },
  {
    id: 'head.reset',
    label: '回正',
    aliases: ['回正', '正视', '复位', 'reset', '看向我'],
    description: '云台回中并正对用户。',
    actuators: ['head'],
    durationMs: 500,
    interruptible: true,
    priority: 20,
    params: [],
    keyframes: [
      { t: 0, pose: { headYaw: 0, headPitch: 0, headRoll: 0 } },
      { t: 1, pose: { headYaw: 0, headPitch: 0, headRoll: 0 } },
    ],
  },

  // ───────────────────────── 屏幕表情 ─────────────────────────
  {
    id: 'screen.set_expression',
    label: '切换表情',
    aliases: ['表情', '笑', '显示', 'expression', '开心', '难过'],
    description: '切换屏幕表情，配合语音表达情绪。',
    actuators: ['screen'],
    durationMs: 400,
    interruptible: true,
    priority: 20,
    params: [
      {
        name: 'expression',
        description:
          '表情：neutral/happy/joy/sad/angry/surprise/sleepy/focus/heart/question/error/loading',
        type: 'enum',
        required: true,
        default: 'neutral',
        options: [
          'neutral',
          'happy',
          'joy',
          'sad',
          'angry',
          'surprise',
          'sleepy',
          'focus',
          'heart',
          'question',
          'error',
          'loading',
        ],
      },
      {
        name: 'holdMs',
        description: '保持时长，毫秒',
        type: 'number',
        required: false,
        default: 1200,
        min: 200,
        max: 10000,
      },
    ],
    keyframes: [
      { t: 0, pose: {} },
      { t: 1, pose: {} },
    ],
  },
  {
    id: 'screen.blink',
    label: '眨眼',
    aliases: ['眨眼', 'blink', '闭眼'],
    description: '屏幕眨眼动画，用于增加生动感。',
    actuators: ['screen'],
    durationMs: 400,
    interruptible: true,
    priority: 10,
    params: [
      {
        name: 'times',
        description: '眨眼次数',
        type: 'number',
        required: false,
        default: 1,
        min: 1,
        max: 3,
      },
    ],
    keyframes: [
      { t: 0, pose: { eyeOpen: 1 } },
      { t: 0.45, pose: { eyeOpen: 0 } },
      { t: 0.6, pose: { eyeOpen: 1 } },
      { t: 1, pose: { eyeOpen: 1 } },
    ],
  },

  // ───────────────────────── 机械臂 ─────────────────────────
  {
    id: 'arm.wave',
    label: '挥手',
    aliases: ['挥手', '打招呼', 'hi', 'hello', '再见', 'wave'],
    description: '抬起手臂左右摆动，用于打招呼和告别。',
    actuators: ['arm'],
    durationMs: 1600,
    interruptible: false,
    priority: 60,
    params: [
      {
        name: 'times',
        description: '挥手次数',
        type: 'number',
        required: false,
        default: 3,
        min: 1,
        max: 5,
      },
      {
        name: 'hand',
        description: '用哪只手',
        type: 'enum',
        required: false,
        default: 'right',
        options: ['left', 'right'],
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, wrist: 0 } },
      { t: 0.2, pose: { shoulder: 85, elbow: 30, wrist: -10 } },
      { t: 0.35, pose: { shoulder: 85, elbow: 30, wrist: 25 } },
      { t: 0.5, pose: { shoulder: 85, elbow: 30, wrist: -25 } },
      { t: 0.65, pose: { shoulder: 85, elbow: 30, wrist: 25 } },
      { t: 0.8, pose: { shoulder: 80, elbow: 35, wrist: 0 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, wrist: 0 } },
    ],
    emotion: 'happy',
  },
  {
    id: 'arm.point',
    label: '指向',
    aliases: ['指', '指向', '那边', 'point', '你看'],
    description: '手臂伸直指向某个方向，同时云台跟随。',
    actuators: ['arm', 'head'],
    durationMs: 1100,
    interruptible: false,
    priority: 65,
    params: [
      {
        name: 'direction',
        description: '指向',
        type: 'enum',
        required: false,
        default: 'left',
        options: ['left', 'right', 'up', 'down', 'forward'],
      },
      {
        name: 'holdMs',
        description: '指向保持时长，毫秒',
        type: 'number',
        required: false,
        default: 1200,
        min: 300,
        max: 8000,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, headYaw: 0, headPitch: 0 } },
      { t: 0.4, pose: { shoulder: 75, elbow: 5, headYaw: 45, headPitch: 5 } },
      { t: 0.8, pose: { shoulder: 75, elbow: 5, headYaw: 45, headPitch: 5 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, headYaw: 0, headPitch: 0 } },
    ],
  },
  {
    id: 'arm.present',
    label: '展示介绍',
    aliases: ['介绍', '展示', '请看', 'present', '介绍给你'],
    description: '摊开手掌做介绍姿势。',
    actuators: ['arm', 'head'],
    durationMs: 1400,
    interruptible: false,
    priority: 60,
    params: [],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, wrist: 0, gripper: 0 } },
      { t: 0.4, pose: { shoulder: 55, elbow: 45, wrist: 20, gripper: 0 } },
      { t: 0.75, pose: { shoulder: 58, elbow: 48, wrist: 22, gripper: 0 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, wrist: 0, gripper: 0 } },
    ],
    emotion: 'happy',
  },
  {
    id: 'arm.give',
    label: '递出物品',
    aliases: ['递', '给你', '拿走', '交付', 'give', '接收'],
    description: '夹爪抓住物体后向前递出，随后松开。',
    actuators: ['arm'],
    durationMs: 2200,
    interruptible: false,
    priority: 75,
    params: [
      {
        name: 'holdMs',
        description: '递出后保持时长，毫秒',
        type: 'number',
        required: false,
        default: 900,
        min: 200,
        max: 5000,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, wrist: 0, gripper: 0 } },
      { t: 0.25, pose: { shoulder: 40, elbow: 55, wrist: 0, gripper: 1 } },
      { t: 0.5, pose: { shoulder: 70, elbow: 20, wrist: 10, gripper: 1 } },
      { t: 0.72, pose: { shoulder: 72, elbow: 18, wrist: 10, gripper: 1 } },
      { t: 0.8, pose: { shoulder: 72, elbow: 18, wrist: 10, gripper: 0 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, wrist: 0, gripper: 0 } },
    ],
    emotion: 'happy',
  },
  {
    id: 'arm.thumbs_up',
    label: '竖大拇指',
    aliases: ['点赞', '大拇指', '棒', 'thumbs up', '好评', '干得好'],
    description: '握拳竖起拇指，表示赞许。',
    actuators: ['arm'],
    durationMs: 1500,
    interruptible: false,
    priority: 60,
    params: [
      {
        name: 'holdMs',
        description: '保持时长，毫秒',
        type: 'number',
        required: false,
        default: 1000,
        min: 200,
        max: 5000,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, wrist: 0, gripper: 0 } },
      { t: 0.35, pose: { shoulder: 60, elbow: 90, wrist: -20, gripper: 0.9 } },
      { t: 0.75, pose: { shoulder: 60, elbow: 90, wrist: -20, gripper: 0.9 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, wrist: 0, gripper: 0 } },
    ],
    emotion: 'joy',
  },
  {
    id: 'arm.bow',
    label: '鞠躬',
    aliases: ['鞠躬', '行礼', '致意', 'bow', '行礼'],
    description: '身体前倾并低头，表示尊敬或致谢。',
    actuators: ['arm', 'body', 'head'],
    durationMs: 1800,
    interruptible: false,
    priority: 70,
    params: [
      {
        name: 'depth',
        description: '前倾幅度，度，10 到 40',
        type: 'number',
        required: false,
        default: 25,
        min: 10,
        max: 40,
      },
    ],
    keyframes: [
      { t: 0, pose: { bodyLean: 0, headPitch: 0, shoulder: 0 } },
      { t: 0.35, pose: { bodyLean: 25, headPitch: 14, shoulder: 20 } },
      { t: 0.6, pose: { bodyLean: 25, headPitch: 14, shoulder: 20 } },
      { t: 1, pose: { bodyLean: 0, headPitch: 0, shoulder: 0 } },
    ],
    emotion: 'neutral',
  },
  {
    id: 'arm.pick',
    label: '抓取',
    aliases: ['抓', '拿起', '捡', 'pick', '取'],
    description: '机械臂下降、闭合夹爪抓取物体并抬起。',
    actuators: ['arm'],
    durationMs: 2000,
    interruptible: false,
    priority: 75,
    params: [
      {
        name: 'force',
        description: '夹持力度，0.3 到 1',
        type: 'number',
        required: false,
        default: 0.7,
        min: 0.3,
        max: 1,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, gripper: 0 } },
      { t: 0.3, pose: { shoulder: 15, elbow: 60, gripper: 0 } },
      { t: 0.55, pose: { shoulder: 15, elbow: 60, gripper: 0.7 } },
      { t: 0.8, pose: { shoulder: 55, elbow: 25, gripper: 0.7 } },
      { t: 1, pose: { shoulder: 40, elbow: 30, gripper: 0.7 } },
    ],
  },
  {
    id: 'arm.release',
    label: '放下',
    aliases: ['放下', '松手', '释放', 'release', 'put down'],
    description: '机械臂下降并松开夹爪释放物体。',
    actuators: ['arm'],
    durationMs: 1600,
    interruptible: false,
    priority: 75,
    params: [],
    keyframes: [
      { t: 0, pose: { shoulder: 40, elbow: 30, gripper: 0.7 } },
      { t: 0.45, pose: { shoulder: 15, elbow: 60, gripper: 0.7 } },
      { t: 0.6, pose: { shoulder: 15, elbow: 60, gripper: 0 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, gripper: 0 } },
    ],
  },
  {
    id: 'arm.pump_fist',
    label: '握拳加油',
    aliases: ['加油', '打气', '你可以的', 'pump', '鼓劲'],
    description: '握拳上下挥动，为用户鼓劲。',
    actuators: ['arm'],
    durationMs: 1700,
    interruptible: false,
    priority: 65,
    params: [
      {
        name: 'times',
        description: '挥动次数',
        type: 'number',
        required: false,
        default: 3,
        min: 1,
        max: 5,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, gripper: 0 } },
      { t: 0.2, pose: { shoulder: 70, elbow: 80, gripper: 1 } },
      { t: 0.4, pose: { shoulder: 40, elbow: 80, gripper: 1 } },
      { t: 0.6, pose: { shoulder: 70, elbow: 80, gripper: 1 } },
      { t: 0.8, pose: { shoulder: 40, elbow: 80, gripper: 1 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, gripper: 0 } },
    ],
    emotion: 'excited',
  },
  {
    id: 'arm.scratch_head',
    label: '挠头',
    aliases: ['挠头', '尴尬', '不好意思', 'scratch', '摸头'],
    description: '抬手挠后脑勺，表示尴尬或为难。',
    actuators: ['arm', 'head'],
    durationMs: 2000,
    interruptible: false,
    priority: 60,
    params: [],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, headPitch: 0, headYaw: 0 } },
      { t: 0.3, pose: { shoulder: 95, elbow: 100, headPitch: -8, headYaw: -15 } },
      { t: 0.55, pose: { shoulder: 95, elbow: 100, headPitch: -8, headYaw: -25 } },
      { t: 0.8, pose: { shoulder: 95, elbow: 100, headPitch: -8, headYaw: -15 } },
      { t: 1, pose: { shoulder: 0, elbow: 10, headPitch: 0, headYaw: 0 } },
    ],
    emotion: 'confused',
  },
  {
    id: 'arm.cover_face',
    label: '捂脸',
    aliases: ['捂脸', '羞', '不好意思', '害羞', 'cover'],
    description: '双手抬至面前遮住屏幕，表达害羞。',
    actuators: ['arm', 'screen'],
    durationMs: 1800,
    interruptible: false,
    priority: 65,
    params: [
      {
        name: 'holdMs',
        description: '遮挡保持时长，毫秒',
        type: 'number',
        required: false,
        default: 900,
        min: 200,
        max: 4000,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, elbow: 10, screenExpr: 'happy' } },
      { t: 0.35, pose: { shoulder: 80, elbow: 95, screenExpr: 'happy' } },
      { t: 0.7, pose: { shoulder: 80, elbow: 95, screenExpr: 'happy' } },
      { t: 1, pose: { shoulder: 0, elbow: 10, screenExpr: 'neutral' } },
    ],
    emotion: 'happy',
  },
  {
    id: 'arm.shrug',
    label: '耸肩',
    aliases: ['耸肩', '不知道', '随便', '无所谓', 'shrug'],
    description: '双肩抬起，表示不知道或无奈。',
    actuators: ['arm', 'head'],
    durationMs: 1500,
    interruptible: false,
    priority: 60,
    params: [
      {
        name: 'holdMs',
        description: '保持时长，毫秒',
        type: 'number',
        required: false,
        default: 800,
        min: 200,
        max: 4000,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, headRoll: 0, headYaw: 0 } },
      { t: 0.35, pose: { shoulder: 30, headRoll: 8, headYaw: -6 } },
      { t: 0.7, pose: { shoulder: 30, headRoll: 8, headYaw: -6 } },
      { t: 1, pose: { shoulder: 0, headRoll: 0, headYaw: 0 } },
    ],
    emotion: 'confused',
  },
  {
    id: 'arm.dance',
    label: '跳舞',
    aliases: ['跳舞', '舞', 'dance', '扭', '庆祝'],
    description: '身体与手臂配合做一段欢快的舞蹈。',
    actuators: ['arm', 'body', 'head', 'screen'],
    durationMs: 3000,
    interruptible: false,
    priority: 80,
    params: [
      {
        name: 'intensity',
        description: '幅度，0.4 到 1',
        type: 'number',
        required: false,
        default: 0.8,
        min: 0.4,
        max: 1,
      },
    ],
    keyframes: [
      { t: 0, pose: { shoulder: 0, bodyLean: 0, headYaw: 0, screenExpr: 'joy' } },
      { t: 0.15, pose: { shoulder: 60, bodyLean: -8, headYaw: -18, screenExpr: 'joy' } },
      { t: 0.3, pose: { shoulder: 20, bodyLean: 8, headYaw: 18, screenExpr: 'joy' } },
      { t: 0.45, pose: { shoulder: 65, bodyLean: -8, headYaw: -18, screenExpr: 'joy' } },
      { t: 0.6, pose: { shoulder: 20, bodyLean: 8, headYaw: 18, screenExpr: 'joy' } },
      { t: 0.75, pose: { shoulder: 60, bodyLean: -6, headYaw: -16, screenExpr: 'joy' } },
      { t: 1, pose: { shoulder: 0, bodyLean: 0, headYaw: 0, screenExpr: 'happy' } },
    ],
    emotion: 'joy',
  },

  // ───────────────────────── 移动底盘 ─────────────────────────
  {
    id: 'base.move',
    label: '移动',
    aliases: ['移动', '走', '前进', '后退', '过来', '过去', 'move', '靠近'],
    description: '底盘朝指定方向平移指定距离。',
    actuators: ['base'],
    durationMs: 1400,
    interruptible: false,
    priority: 70,
    conflictGroup: ROBOT_SPEC.conflictGroupBase,
    params: [
      {
        name: 'direction',
        description: '移动方向',
        type: 'enum',
        required: true,
        default: 'forward',
        options: ['forward', 'backward', 'left', 'right'],
      },
      {
        name: 'distanceCm',
        description: '移动距离，厘米，5 到 120',
        type: 'number',
        required: false,
        default: 40,
        min: 5,
        max: 120,
      },
    ],
    keyframes: [
      { t: 0, pose: { baseX: 0, baseZ: 0 } },
      { t: 0.2, pose: { baseX: 0, baseZ: 0 } },
      { t: 0.85, pose: { baseX: 0, baseZ: 0 } },
      { t: 1, pose: { baseX: 0, baseZ: 0 } },
    ],
  },
  {
    id: 'base.rotate',
    label: '转向',
    aliases: ['转身', '转向', '转过去', 'rotate', '转圈', '看那边'],
    description: '底盘原地旋转指定角度。',
    actuators: ['base', 'head'],
    durationMs: 1200,
    interruptible: false,
    priority: 70,
    conflictGroup: ROBOT_SPEC.conflictGroupBase,
    params: [
      {
        name: 'direction',
        description: '转向',
        type: 'enum',
        required: false,
        default: 'left',
        options: ['left', 'right', 'around'],
      },
      {
        name: 'angleDeg',
        description: '旋转角度，度，15 到 180；around 时忽略',
        type: 'number',
        required: false,
        default: 90,
        min: 15,
        max: 180,
      },
    ],
    keyframes: [
      { t: 0, pose: { baseHeading: 0, headYaw: 0 } },
      { t: 0.2, pose: { baseHeading: 0, headYaw: 0 } },
      { t: 0.85, pose: { baseHeading: 0, headYaw: 0 } },
      { t: 1, pose: { baseHeading: 0, headYaw: 0 } },
    ],
  },
  {
    id: 'base.return_home',
    label: '回到原位',
    aliases: ['回去', '回家', '归位', '回来原位', 'home', '回位'],
    description: '底盘回到初始坐标并朝向用户。',
    actuators: ['base'],
    durationMs: 1800,
    interruptible: false,
    priority: 75,
    conflictGroup: ROBOT_SPEC.conflictGroupBase,
    params: [],
    keyframes: [
      { t: 0, pose: { baseX: 0, baseZ: 0, baseHeading: 0 } },
      { t: 1, pose: { baseX: 0, baseZ: 0, baseHeading: 0 } },
    ],
  },
  {
    id: 'base.stop',
    label: '停止',
    aliases: ['停', '停下', '别动', 'stop', '站住', '安静'],
    description: '立即停止当前所有动作，回到待机姿态。',
    actuators: ['base', 'arm', 'head'],
    durationMs: 300,
    interruptible: false,
    priority: 99,
    params: [],
    keyframes: [
      { t: 0, pose: {} },
      { t: 1, pose: {} },
    ],
  },

  // ───────────────────────── 语音 / 声音 ─────────────────────────
  {
    id: 'audio.beep',
    label: '提示音',
    aliases: ['滴', ' beep', '提示音', '哔'],
    description: '播放一声短促提示音，常用于确认收到指令。',
    actuators: ['audio'],
    durationMs: 250,
    interruptible: true,
    priority: 25,
    params: [
      {
        name: 'count',
        description: '响几声',
        type: 'number',
        required: false,
        default: 1,
        min: 1,
        max: 3,
      },
    ],
    keyframes: [
      { t: 0, pose: {} },
      { t: 1, pose: {} },
    ],
  },
  {
    id: 'audio.laugh',
    label: '笑声',
    aliases: ['笑', '哈哈', 'laugh', '开心'],
    description: '播放一段轻快笑声。',
    actuators: ['audio'],
    durationMs: 900,
    interruptible: true,
    priority: 30,
    params: [],
    keyframes: [
      { t: 0, pose: {} },
      { t: 1, pose: {} },
    ],
    emotion: 'happy',
  },

  // ───────────────────────── 待机 / 呼吸 ─────────────────────────
  {
    id: 'body.idle_breathe',
    label: '待机呼吸',
    aliases: ['呼吸', '待机', 'idle', '休息'],
    description: '呼吸起伏的待机循环，让机器人保持生命感。',
    actuators: ['body', 'head'],
    durationMs: 4000,
    interruptible: true,
    priority: 10,
    params: [
      {
        name: 'cycles',
        description: '呼吸次数',
        type: 'number',
        required: false,
        default: 2,
        min: 1,
        max: 5,
      },
    ],
    keyframes: [
      { t: 0, pose: { bodyLean: 0, headPitch: 0 } },
      { t: 0.25, pose: { bodyLean: -3, headPitch: -3 } },
      { t: 0.5, pose: { bodyLean: 0, headPitch: 0 } },
      { t: 0.75, pose: { bodyLean: 3, headPitch: 2 } },
      { t: 1, pose: { bodyLean: 0, headPitch: 0 } },
    ],
    emotion: 'neutral',
  },
  {
    id: 'body.sleep',
    label: '进入睡眠',
    aliases: ['睡觉', '休息', '休眠', 'sleep', '晚安'],
    description: '闭眼低头进入睡眠待机。',
    actuators: ['body', 'head', 'screen'],
    durationMs: 3000,
    interruptible: true,
    priority: 50,
    params: [],
    keyframes: [
      { t: 0, pose: { eyeOpen: 1, headPitch: 0, bodyLean: 0, screenExpr: 'neutral' } },
      { t: 0.6, pose: { eyeOpen: 0.05, headPitch: -12, bodyLean: 5, screenExpr: 'sleepy' } },
      { t: 1, pose: { eyeOpen: 0.05, headPitch: -12, bodyLean: 5, screenExpr: 'sleepy' } },
    ],
    emotion: 'sleepy',
  },
  {
    id: 'body.wake',
    label: '唤醒',
    aliases: ['唤醒', '醒醒', '起床', 'wake', '醒'],
    description: '睁眼抬头，回到清醒状态。',
    actuators: ['body', 'head', 'screen'],
    durationMs: 1500,
    interruptible: true,
    priority: 55,
    params: [],
    keyframes: [
      { t: 0, pose: { eyeOpen: 0.05, headPitch: -12, bodyLean: 5, screenExpr: 'sleepy' } },
      { t: 0.35, pose: { eyeOpen: 1, headPitch: 12, bodyLean: -6, screenExpr: 'surprise' } },
      { t: 0.7, pose: { eyeOpen: 1, headPitch: 4, bodyLean: 0, screenExpr: 'happy' } },
      { t: 1, pose: { eyeOpen: 1, headPitch: 0, bodyLean: 0, screenExpr: 'neutral' } },
    ],
    emotion: 'excited',
  },
];

/** id -> action 的索引，构建一次复用 */
export const ACTION_MAP: ReadonlyMap<string, RobotAction> = new Map(
  ACTION_LIBRARY.map((a) => [a.id, a]),
);

/** 供 LLM 阅读的动作库文本描述 */
export function describeLibraryForPrompt(): string {
  return ACTION_LIBRARY.map((a) => {
    const params = a.params
      .map((p) => {
        const range =
          p.type === 'number' && p.min !== undefined && p.max !== undefined
            ? `(${p.min}~${p.max})`
            : p.type === 'enum' && p.options
              ? `(${p.options.join('|')})`
              : '';
        return `${p.name}:${p.type}${range}${p.required ? '*' : ''}=${p.default ?? ''}`;
      })
      .join(', ');
    const actuators = a.actuators.join('+');
    return [
      `- ${a.id} [${a.label}]`,
      `  描述: ${a.description}`,
      `  执行器: ${actuators} | 时长: ${a.durationMs}ms | 优先级: ${a.priority} | 可打断: ${a.interruptible ? '是' : '否'}`,
      params ? `  参数: ${params}` : '  参数: 无',
    ].join('\n');
  }).join('\n');
}
